name: CI/CD para Aplicação Java com Maven

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2

      - name: Configurar JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Instalar o Maven
        run: sudo apt-get install -y maven

      - name: Construir o aplicativo
        run: mvn package

      - name: Executar testes
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2

      - name: Configurar JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Instalar o Maven
        run: sudo apt-get install -y maven

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir imagem do Docker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app .

      - name: Tag da imagem do Docker
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my-app ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

      - name: Enviar imagem para o Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
